//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonFileCreatorFromExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phy
    {
        public int Id { get; set; }
        public string CLASSID { get; set; }
        public string CATEGORY { get; set; }
        public string DRUG { get; set; }
        public string ARV { get; set; }
        public string PK { get; set; }
    }
}
